### ISSUE TITLE
Failed to connect wine-platform

### ISSUE THREAD

**Issue by peter0193** [mmtrt/cncra#3] opened 2018-11-08 19:01 UTC
After few months of seamless playing suddenly game stopped launching.
Terminal output after running a game with `/snap/bin/cncra` :
`You need to connect this snap to the wine-platform snap.`

`snap disconnect cncra:wine-platform-plug`
`snap install wine-platform`
`snap connect cncra:wine-platform-plug wine-platform:wine-base-stable`

After doing so and trying to launch game once again:
`/snap/cncra/33/bin/sommelier: line 354: /snap/cncra/33/wine-platform/usr/bin/yad: cannot execute binary file: Exec format error`
`/snap/cncra/33/bin/sommelier: line 358: /snap/cncra/33/wine-platform/usr/bin/yad: cannot execute binary file: Exec format error`
`grep: /home/piotr/snap/cncra/common/.wine/*.reg: No such file or directory`
`------------------------------------------------------`
`WINEPREFIX INFO:`
`Drive C: total 12`
`drwxrwxr-x 3 piotr piotr 4096 Nov  8 11:32 .`
`drwxrwxr-x 4 piotr piotr 4096 Nov  8 11:32 ..`
`drwxrwxr-x 3 piotr piotr 4096 Nov  8 11:32 windows`

`Registry info:`
`/home/piotr/snap/cncra/common/.wine/*.reg:`
`------------------------------------------------------`
`------------------------------------------------------`
`wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: could not exec wineserver" `
`------------------------------------------------------`
`/snap/cncra/33/bin/sommelier: line 101: /snap/cncra/33/wine-platform/usr/bin/yad: cannot execute binary file: Exec format error`

I have also tried removing and installing cncra, but it didn't help. What could be the problem? Since the game have been working for the last time, I've don only some minor system updates.

**Comment by mmtrt** [comment] 2018-11-08 19:16
Yeah I've changed wine base snap and can you paste info of,

`snap interfaces cncra`
`snap interfaces wine-platform`

**Comment by peter0193** [comment] 2018-11-08 19:35
`$ snap interfaces cncra`
`Slot                            Plug`
`:desktop                        cncra,cnctsun`
`:desktop-legacy                 cncra,cnctsun`
`:home                           cncra,cnctsun`
`:network                        cncra,cnctsun`
`:network-bind                   cncra,cnctsun`
`:opengl                         cncra,cnctsun`
`:pulseaudio                     cncra,cnctsun`
`:wayland                        cncra,cnctsun`
`:x11                            cncra,cnctsun`
`wine-platform:wine-base-stable  cncra:wine-platform-plug`
`-                               cncra:hardware-observe`
`-                               cncra:joystick`
`-                               cncra:process-control`

`$ snap interfaces wine-platform`
`Slot                             Plug`
`wine-platform:wine-base-devel    -`
`wine-platform:wine-base-stable   cncra:wine-platform-plug`
`wine-platform:wine-base-staging  -`

**Comment by mmtrt** [comment] 2018-11-08 19:42
looks fine to me, can you paste info

`snap version`
`snap info core`

**Comment by peter0193** [comment] 2018-11-08 19:50
`$ snap version`
`snap    2.35.5`
`snapd   2.35.5`
`series  16`
`ubuntu  18.04`
`kernel  4.15.0-38-generic`


`$ snap info core`
`name:      core`
`summary:   snapd runtime environment`
`publisher: Canonical✓`
`contact:   snaps@canonical.com`
`license:   unset`
`description: |`
`  The core runtime environment for snapd`
`type:         core`
`snap-id:      99T7MUlRhtI3U0QFgl5mXXESAiSwt776`
`tracking:     stable`
`refresh-date: 7 days ago, at 10:57 CET`
`channels:           `                             
`  stable:    16-2.35.5               (5743) 86MB -`
`  candidate: 16-2.35.5               (5743) 86MB -`
`  beta:      16-2.36                 (5797) 86MB -`
`  edge:      16-2.36+git1001.e5411fe (5886) 87MB -`
`installed:   16-2.35.5               (5743) 86MB core`

**Comment by mmtrt** [comment] 2018-11-08 20:01
all info is correct no issue there though I've just tested this snap on two different systems could not reproduce that issue you are having, could you try removing snap data dir `$HOME/snap/cncra` then run `cncra`

**Comment by peter0193** [comment] 2018-11-08 20:46
It didn't help :/

**Comment by mmtrt** [comment] 2018-11-08 20:53
```
snap remove cncra
snap remove wine-platform
snap remove wine-platform-i386
```
reboot system then install cncra

EDIT: I'm currently setting up `Ubuntu 18.04` I'll investigate this issue.

EDIT2: It's working fine no issues on liveboot.
![screenshot from 2018-11-09 05-05-21](https://user-images.githubusercontent.com/2322598/48245036-caeaee00-e40a-11e8-80b1-bf87394bb53e.png)

**Comment by peter0193** [comment] 2018-11-09 12:24
The error still occurs. I have no idea what is going on.
I will try to reinstall snap.

**Comment by mmtrt** [comment] 2018-11-09 12:30
I'm out of ideas, do other wine app snaps works for you at this moment or only this snap does not work?

**Comment by peter0193** [comment] 2018-11-09 12:37
The only other one I have is cnctsun and it doesn't work either.
Snap uses my system wine-devel package, right? Maybe reinstalling it could help?

**Comment by mmtrt** [comment] 2018-11-09 13:00
no they use wine-platform snap which provides wine versions so it doesn't use system wide wine.

**Comment by mmtrt** [comment] 2018-11-09 13:27
~~* Download this old revision snap of `cncra`~~
~~[cncra_32.tar.gz](https://github.com/mmtrt/cncra/files/2565982/cncra_32.tar.gz)~~
~~* Unpack it~~
~~* Open terminal where this snap was unpacked.~~
~~* Install this snap.~~
~~`snap install ./cncra_32.snap --dangerous`~~
~~`snap install wine-platform-i386`~~
~~`snap connect cncra:wine-platform-plug wine-platform-i386:wine-base-stable`~~
~~Note:~~
~~**wine-platform-i386** - Which I've deprecated so that snap will no longer be updated.~~

**Comment by mmtrt** [comment] 2018-11-09 13:43
which system architecture you are running is it i386 or amd64?
post results
`uname -romi`

**Comment by peter0193** [comment] 2018-11-09 14:09
It's pretty old machine
`4.15.0-38-generic i686 i686 GNU/Linux`

**Comment by mmtrt** [comment] 2018-11-09 14:23
thanks it's a `wine-platform` architecture issue I'm working on it will post when its updated & fixed

**Comment by mmtrt** [comment] 2018-11-10 04:59
This issue is now resolved I've now tested `cncra` & `cnctsun` both working on `i386` system.

**Update the snaps**
`snap refresh`

**If issue is still there then cleanslate do the following**
```
snap remove wine-platform
snap remove wine-platform-i386
snap remove cncra
snap remove cnctsun
```
Then install again
```
snap install cncra
snap install cnctsun
```

**Comment by mmtrt** [comment] 2018-11-11 04:31
Closing this as the issue is no longer exists during my testings on i386.

**Closed as completed by mmtrt** 2018-11-11 04:31 UTC
