### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by jfabdo** [mmtrt/cncra#2] opened 2018-09-09 02:47 UTC
On fresh 18.04-1 Ubuntu install, Red Alert prints the following error:
    `Failed to load module "canberra-gtk-module"`

It does not launch from snap store and fails silently. Running the following line fixes it:

    `sudo apt install libcanberra-gtk-module:i386`

**Comment by mmtrt** [comment] 2018-09-09 14:37
just tested the snap on fresh install of `18.04.1` updated I can not reproduce that issue game just works fine installed and launched from `ubuntu software` also tried launching it from `terminal`

**Comment by jfabdo** [comment] 2018-09-10 21:09
@mmtrt the suggestion is that it requires an update before running it from 18.04.1?

**Comment by mmtrt** [comment] 2018-09-11 03:14
It is necessary to update though one user had issues with npp snap was failing because he was using old version of snapd.

**Comment by FunkyFr3sh** [comment] 2018-09-20 19:21
I'm getting this error now too with my old ubuntu installation that i used for testing the snap. Everything used to work fine before, is this related to a update you did to the snap?

Edit: It worked when i started it manually via command line rather than using ubuntu software

**Comment by mmtrt** [comment] 2018-09-22 06:00
I've added that package in `wine-platform` snap should fix this issue.
* Run `snap refresh` command to update.

**Comment by mmtrt** [comment] 2018-11-11 04:34
The canberra stuff is fine and normal (it just tells you that it wont play sound events for button clicks and other GTK events), that isnt fatal or anything so closing this issue.

**Closed as completed by mmtrt** 2018-11-11 04:34 UTC
